import dayjs from 'dayjs';
import ProjectDetail from '@domain/entities/ProjectDetail';

export const MockData: ProjectDetail[] = [
  {
    id: 1,
    name: 'Project Alpha',
    description: 'Developing an AI chatbot',
    from: dayjs('2022-01-01').valueOf(),
    to: dayjs('2023-01-01').valueOf(),
    budget: 50000,
    country: 'USA',
    domain: 'AI',
  },
  {
    id: 2,
    name: 'Project Beta',
    description: 'Building a social media app',
    from: dayjs('2021-03-15').valueOf(),
    to: dayjs('2022-03-15').valueOf(),
    budget: 75000,
    country: 'Canada',
    domain: 'Social Media',
  },
  {
    id: 3,
    name: 'Project Gamma',
    description: 'E-commerce platform development',
    from: dayjs('2020-06-01').valueOf(),
    to: dayjs('2021-06-01').valueOf(),
    budget: 120000,
    country: 'UK',
    domain: 'E-commerce',
  },
  {
    id: 4,
    name: 'Project Delta',
    description: 'Cloud infrastructure setup',
    from: dayjs('2021-04-10').valueOf(),
    to: dayjs('2023-04-10').valueOf(),
    budget: 95000,
    country: 'Germany',
    domain: 'Cloud',
  },
  {
    id: 5,
    name: 'Project Epsilon',
    description: 'Healthcare management system',
    from: dayjs('2023-02-01').valueOf(),
    to: dayjs('2024-02-01').valueOf(),
    budget: 150000,
    country: 'France',
    domain: 'Healthcare',
  },
  {
    id: 6,
    name: 'Project Zeta',
    description: 'Blockchain-based payment system',
    from: dayjs('2022-07-01').valueOf(),
    to: dayjs('2023-07-01').valueOf(),
    budget: 200000,
    country: 'Singapore',
    domain: 'Blockchain',
  },
  {
    id: 7,
    name: 'Project Eta',
    description: 'Real-time collaboration tool',
    from: dayjs('2020-08-20').valueOf(),
    to: dayjs('2021-08-20').valueOf(),
    budget: 30000,
    country: 'Australia',
    domain: 'Collaboration',
  },
  {
    id: 8,
    name: 'Project Theta',
    description: 'Smart home automation',
    from: dayjs('2022-09-01').valueOf(),
    to: dayjs('2024-09-01').valueOf(),
    budget: 110000,
    country: 'Netherlands',
    domain: 'IoT',
  },
  {
    id: 9,
    name: 'Project Iota',
    description: 'EdTech platform for learning',
    from: dayjs('2023-01-15').valueOf(),
    to: dayjs('2025-01-15').valueOf(),
    budget: 90000,
    country: 'India',
    domain: 'Education',
  },
  {
    id: 10,
    name: 'Project Kappa',
    description: 'AR/VR application for training',
    from: dayjs('2021-11-01').valueOf(),
    to: dayjs('2022-11-01').valueOf(),
    budget: 60000,
    country: 'Japan',
    domain: 'AR/VR',
  },
  {
    id: 11,
    name: 'Project Lambda',
    description: 'Cybersecurity software suite',
    from: dayjs('2023-05-01').valueOf(),
    to: dayjs('2024-05-01').valueOf(),
    budget: 130000,
    country: 'Israel',
    domain: 'Cybersecurity',
  },
  {
    id: 12,
    name: 'Project Mu',
    description: 'Big data analytics tool',
    from: dayjs('2020-02-01').valueOf(),
    to: dayjs('2021-02-01').valueOf(),
    budget: 180000,
    country: 'China',
    domain: 'Big Data',
  },
  {
    id: 13,
    name: 'Project Nu',
    description: 'Automated drone delivery',
    from: dayjs('2022-03-01').valueOf(),
    to: dayjs('2024-03-01').valueOf(),
    budget: 240000,
    country: 'USA',
    domain: 'Logistics',
  },
  {
    id: 14,
    name: 'Project Xi',
    description: 'Autonomous vehicle navigation',
    from: dayjs('2021-12-01').valueOf(),
    to: dayjs('2023-12-01').valueOf(),
    budget: 320000,
    country: 'South Korea',
    domain: 'Automotive',
  },
  {
    id: 15,
    name: 'Project Omicron',
    description: 'Wearable health tracker',
    from: dayjs('2020-01-01').valueOf(),
    to: dayjs('2021-01-01').valueOf(),
    budget: 75000,
    country: 'Sweden',
    domain: 'Healthcare',
  },
  {
    id: 16,
    name: 'Project Pi',
    description: 'SaaS platform for freelancers',
    from: dayjs('2022-05-01').valueOf(),
    to: dayjs('2023-05-01').valueOf(),
    budget: 95000,
    country: 'USA',
    domain: 'SaaS',
  },
  {
    id: 17,
    name: 'Project Rho',
    description: 'Mobile game development',
    from: dayjs('2021-06-01').valueOf(),
    to: dayjs('2022-06-01').valueOf(),
    budget: 30000,
    country: 'Brazil',
    domain: 'Gaming',
  },
  {
    id: 18,
    name: 'Project Sigma',
    description: 'Online banking app',
    from: dayjs('2023-02-01').valueOf(),
    to: dayjs('2024-02-01').valueOf(),
    budget: 200000,
    country: 'UK',
    domain: 'FinTech',
  },
  {
    id: 19,
    name: 'Project Tau',
    description: 'AI-powered marketing tool',
    from: dayjs('2022-08-01').valueOf(),
    to: dayjs('2023-08-01').valueOf(),
    budget: 110000,
    country: 'Germany',
    domain: 'Marketing',
  },
  {
    id: 20,
    name: 'Project Upsilon',
    description: 'Video streaming platform',
    from: dayjs('2020-04-01').valueOf(),
    to: dayjs('2021-04-01').valueOf(),
    budget: 250000,
    country: 'Australia',
    domain: 'Entertainment',
  },
  {
    id: 21,
    name: 'Project Phi',
    description: 'Augmented reality shopping app',
    from: dayjs('2021-03-01').valueOf(),
    to: dayjs('2023-03-01').valueOf(),
    budget: 140000,
    country: 'Japan',
    domain: 'AR/VR',
  },
  {
    id: 22,
    name: 'Project Chi',
    description: 'Smart agriculture monitoring',
    from: dayjs('2022-10-01').valueOf(),
    to: dayjs('2024-10-01').valueOf(),
    budget: 160000,
    country: 'India',
    domain: 'Agriculture',
  },
  {
    id: 23,
    name: 'Project Psi',
    description: 'Automated legal documentation',
    from: dayjs('2023-01-01').valueOf(),
    to: dayjs('2024-01-01').valueOf(),
    budget: 75000,
    country: 'Canada',
    domain: 'LegalTech',
  },
  {
    id: 24,
    name: 'Project Omega',
    description: 'AI-driven content moderation',
    from: dayjs('2021-07-01').valueOf(),
    to: dayjs('2022-07-01').valueOf(),
    budget: 85000,
    country: 'South Africa',
    domain: 'Media',
  },
  {
    id: 25,
    name: 'Project Ares',
    description: 'Cyber-physical systems security',
    from: dayjs('2022-06-01').valueOf(),
    to: dayjs('2023-06-01').valueOf(),
    budget: 190000,
    country: 'USA',
    domain: 'Cybersecurity',
  },
  {
    id: 26,
    name: 'Project Athena',
    description: 'Virtual reality classroom',
    from: dayjs('2023-08-01').valueOf(),
    to: dayjs('2025-08-01').valueOf(),
    budget: 120000,
    country: 'UK',
    domain: 'Education',
  },
  {
    id: 27,
    name: 'Project Apollo',
    description: 'Sustainable energy grid',
    from: dayjs('2020-01-15').valueOf(),
    to: dayjs('2022-01-15').valueOf(),
    budget: 350000,
    country: 'Germany',
    domain: 'Energy',
  },
  {
    id: 28,
    name: 'Project Artemis',
    description: 'Blockchain identity verification',
    from: dayjs('2021-05-01').valueOf(),
    to: dayjs('2023-05-01').valueOf(),
    budget: 175000,
    country: 'USA',
    domain: 'Blockchain',
  },
  {
    id: 29,
    name: 'Project Hera',
    description: 'Decentralized data storage',
    from: dayjs('2023-04-01').valueOf(),
    to: dayjs('2024-04-01').valueOf(),
    budget: 300000,
    country: 'France',
    domain: 'Cloud',
  },
];
